<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180516073337 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE motinine_baze DROP FOREIGN KEY fkc_BAZE_AUGALU_PAVADINIMAI');
        $this->addSql('ALTER TABLE seklos DROP FOREIGN KEY fkc_SEKLOS_AUGALU_PAVADINIMAI');
        $this->addSql('ALTER TABLE skiepai DROP FOREIGN KEY fkc_SKIEPAI_AUGALU_PAVADINIMAI');
        $this->addSql('ALTER TABLE cheminiai_darbai DROP FOREIGN KEY fkc_CH_DARBAI_CH_DARBU_PAV');
        $this->addSql('ALTER TABLE darbai DROP FOREIGN KEY fkc_DARBAI_CHEMINIAI_DARBAI');
        $this->addSql('ALTER TABLE med_panaudojimas DROP FOREIGN KEY fkc_PANAUDOJIMAS_CHEMINIAI_DARBAI');
        $this->addSql('ALTER TABLE tech_panaudojimas DROP FOREIGN KEY fkc_TECH_PAN_CHEMINIAI_DARBAI');
        $this->addSql('ALTER TABLE darbai DROP FOREIGN KEY fkc_DARBAI_DARBUOTOJAI');
        $this->addSql('ALTER TABLE sejinukai DROP FOREIGN KEY fkc_SEJINUKAI_KILMES');
        $this->addSql('ALTER TABLE seklos DROP FOREIGN KEY fkc_SEKLOS_KILMES');
        $this->addSql('ALTER TABLE skiepai DROP FOREIGN KEY fkc_SKIEPAI_KILMES');
        $this->addSql('ALTER TABLE tech_panaudojimas DROP FOREIGN KEY fkc_TECH_PAN_MED_PANAUDOJIMAS');
        $this->addSql('ALTER TABLE med_panaudojimas DROP FOREIGN KEY fkc_PANAUDOJIMAS_MEDZIAGOS');
        $this->addSql('ALTER TABLE kilmes DROP FOREIGN KEY fkc_KILMES_MOTININE_BAZE');
        $this->addSql('ALTER TABLE darbuotojai DROP FOREIGN KEY fkc_DARBUOTOJAI_PAREIGOS');
        $this->addSql('ALTER TABLE sodinukai DROP FOREIGN KEY fkc_SODINUKAI_PERSODINIMO_BUDAI');
        $this->addSql('ALTER TABLE cheminiai_darbai DROP FOREIGN KEY fkc_CH_DARBAI_SEJINUKAI');
        $this->addSql('ALTER TABLE sodinukai DROP FOREIGN KEY fkc_SODINUKAI_SEJINUKAI');
        $this->addSql('ALTER TABLE techniniai_darbai DROP FOREIGN KEY fkc_TECH_DARBAI_SEJINUKAI');
        $this->addSql('ALTER TABLE sejinukai DROP FOREIGN KEY fkc_SEJINUKAI_SEKLOS');
        $this->addSql('ALTER TABLE skiepyti_augalai DROP FOREIGN KEY fkc_SK_AUGALAI_SKIEPAI');
        $this->addSql('ALTER TABLE skiepyti_augalai DROP FOREIGN KEY fkc_SK_AUGALAI_SKIEPIJIMO_BUDAI');
        $this->addSql('ALTER TABLE cheminiai_darbai DROP FOREIGN KEY fkc_CH_DARBAI_SKIEPYTI_AUGALAI');
        $this->addSql('ALTER TABLE techniniai_darbai DROP FOREIGN KEY fkc_TECH_DARBAI_SKIEPYTI_AUGALAI');
        $this->addSql('ALTER TABLE sejinukai DROP FOREIGN KEY fkc_SEJINUKAI_SKLYPAI');
        $this->addSql('ALTER TABLE cheminiai_darbai DROP FOREIGN KEY fkc_CH_DARBAI_SODINUKAI');
        $this->addSql('ALTER TABLE skiepyti_augalai DROP FOREIGN KEY fkc_SK_AUGALAI_SODINUKAI');
        $this->addSql('ALTER TABLE techniniai_darbai DROP FOREIGN KEY fkc_TECH_DARBAI_SODINUKAI');
        $this->addSql('ALTER TABLE techniniai_darbai DROP FOREIGN KEY fkc_TECH_DARBAI_TECH_DARBU_PAV');
        $this->addSql('ALTER TABLE tech_panaudojimas DROP FOREIGN KEY fkc_TECH_PAN_TECHNIKOS_SARASAS');
        $this->addSql('ALTER TABLE darbai DROP FOREIGN KEY fkc_DARBAI_TECHNINIAI_DARBAI');
        $this->addSql('ALTER TABLE tech_panaudojimas DROP FOREIGN KEY fkc_TECH_PAN_TECHNINIAI_DARBAI');
        $this->addSql('DROP TABLE augalu_pavadinimai');
        $this->addSql('DROP TABLE ch_darbu_pav');
        $this->addSql('DROP TABLE cheminiai_darbai');
        $this->addSql('DROP TABLE darbai');
        $this->addSql('DROP TABLE darbuotojai');
        $this->addSql('DROP TABLE kilmes');
        $this->addSql('DROP TABLE med_panaudojimas');
        $this->addSql('DROP TABLE medziagos');
        $this->addSql('DROP TABLE motinine_baze');
        $this->addSql('DROP TABLE pareigos');
        $this->addSql('DROP TABLE persodinimo_budai');
        $this->addSql('DROP TABLE sejinukai');
        $this->addSql('DROP TABLE seklos');
        $this->addSql('DROP TABLE skiepai');
        $this->addSql('DROP TABLE skiepijimo_budai');
        $this->addSql('DROP TABLE skiepyti_augalai');
        $this->addSql('DROP TABLE sklypai');
        $this->addSql('DROP TABLE sodinukai');
        $this->addSql('DROP TABLE tech_darbu_pav');
        $this->addSql('DROP TABLE tech_panaudojimas');
        $this->addSql('DROP TABLE technikos_sarasas');
        $this->addSql('DROP TABLE techniniai_darbai');
        $this->addSql('ALTER TABLE services CHANGE price price INT NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE augalu_pavadinimai (id_AUGALU_PAVADINIMAI INT AUTO_INCREMENT NOT NULL, rusis VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, gentis VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, forma VARCHAR(255) DEFAULT NULL COLLATE utf16_lithuanian_ci, UNIQUE INDEX id_AUGALU_PAVADINIMAI (id_AUGALU_PAVADINIMAI), PRIMARY KEY(id_AUGALU_PAVADINIMAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ch_darbu_pav (id_CH_DARBU_PAV INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, UNIQUE INDEX id_CH_DARBU_PAV (id_CH_DARBU_PAV), PRIMARY KEY(id_CH_DARBU_PAV)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cheminiai_darbai (id_CHEMINIAI_DARBAI INT AUTO_INCREMENT NOT NULL, data DATE NOT NULL, plotas DOUBLE PRECISION NOT NULL, trukme INT NOT NULL, fk_CH_DARBU_PAV INT NOT NULL, fk_SEJINUKAI INT DEFAULT NULL, fk_SODINUKAI INT DEFAULT NULL, fk_SKIEPYTI_AUGALAI INT DEFAULT NULL, UNIQUE INDEX id_CHEMINIAI_DARBAI (id_CHEMINIAI_DARBAI), INDEX fkc_CH_DARBAI_CH_DARBU_PAV (fk_CH_DARBU_PAV), INDEX fkc_CH_DARBAI_SEJINUKAI (fk_SEJINUKAI), INDEX fkc_CH_DARBAI_SODINUKAI (fk_SODINUKAI), INDEX fkc_CH_DARBAI_SKIEPYTI_AUGALAI (fk_SKIEPYTI_AUGALAI), PRIMARY KEY(id_CHEMINIAI_DARBAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE darbai (id_DARBAI INT AUTO_INCREMENT NOT NULL, fk_CHEMINIAI_DARBAI INT DEFAULT NULL, fk_TECHNINIAI_DARBAI INT DEFAULT NULL, fk_DARBUOTOJAI INT NOT NULL, UNIQUE INDEX id_DARBAI (id_DARBAI), INDEX fkc_DARBAI_CHEMINIAI_DARBAI (fk_CHEMINIAI_DARBAI), INDEX fkc_DARBAI_TECHNINIAI_DARBAI (fk_TECHNINIAI_DARBAI), INDEX fkc_DARBAI_DARBUOTOJAI (fk_DARBUOTOJAI), PRIMARY KEY(id_DARBAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE darbuotojai (asmens_kodas INT AUTO_INCREMENT NOT NULL, vardas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, pavarde VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, dirba_nuo DATE NOT NULL, fk_PAREIGOS INT NOT NULL, UNIQUE INDEX asmens_kodas (asmens_kodas), INDEX fkc_DARBUOTOJAI_PAREIGOS (fk_PAREIGOS), PRIMARY KEY(asmens_kodas)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kilmes (id_KILMES INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) DEFAULT NULL COLLATE utf16_lithuanian_ci, fk_MOTININE_BAZE INT DEFAULT NULL, UNIQUE INDEX id_KILMES (id_KILMES), UNIQUE INDEX fkc_KILMES_MOTININE_BAZE (fk_MOTININE_BAZE), PRIMARY KEY(id_KILMES)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE med_panaudojimas (id_MED_PANAUDOJIMAS INT AUTO_INCREMENT NOT NULL, sanaudos INT NOT NULL, fk_CHEMINIAI_DARBAI INT DEFAULT NULL, fk_MEDZIAGOS INT NOT NULL, UNIQUE INDEX id_MED_PANAUDOJIMAS (id_MED_PANAUDOJIMAS), INDEX fkc_PANAUDOJIMAS_CHEMINIAI_DARBAI (fk_CHEMINIAI_DARBAI), INDEX fkc_PANAUDOJIMAS_MEDZIAGOS (fk_MEDZIAGOS), PRIMARY KEY(id_MED_PANAUDOJIMAS)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medziagos (id_MEDZIAGOS INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, kiekis INT NOT NULL, pirkimo_data DATE NOT NULL, kaina NUMERIC(10, 0) NOT NULL, likutis INT NOT NULL, UNIQUE INDEX id_MEDZIAGOS (id_MEDZIAGOS), PRIMARY KEY(id_MEDZIAGOS)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE motinine_baze (id_MOTININE_BAZE INT AUTO_INCREMENT NOT NULL, fk_AUGALU_PAVADINIMAI INT NOT NULL, metai DATE NOT NULL, kiekis INT NOT NULL, INDEX fkc_BAZE_AUGALU_PAVADINIMAI (fk_AUGALU_PAVADINIMAI), INDEX id_MOTININE_BAZE (id_MOTININE_BAZE), PRIMARY KEY(id_MOTININE_BAZE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pareigos (id_PAREIGOS INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, UNIQUE INDEX id_PAREIGOS (id_PAREIGOS), PRIMARY KEY(id_PAREIGOS)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE persodinimo_budai (id_PERSODINIMO_BUDAI INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, UNIQUE INDEX id_PERSODINIMO_BUDAI (id_PERSODINIMO_BUDAI), PRIMARY KEY(id_PERSODINIMO_BUDAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sejinukai (id_SEJINUKAI INT AUTO_INCREMENT NOT NULL, plotas DOUBLE PRECISION NOT NULL, kiekis INT NOT NULL, kaina NUMERIC(10, 0) NOT NULL, pasodinimo_data DATE NOT NULL, fk_SKLYPAI INT NOT NULL, fk_KILMES INT DEFAULT NULL, fk_SEKLOS INT DEFAULT NULL, UNIQUE INDEX id_SEJINUKAI (id_SEJINUKAI), INDEX fkc_SEJINUKAI_SKLYPAI (fk_SKLYPAI), INDEX fkc_SEJINUKAI_KILMES (fk_KILMES), INDEX fkc_SEJINUKAI_SEKLOS (fk_SEKLOS), PRIMARY KEY(id_SEJINUKAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seklos (id_SEKLOS INT AUTO_INCREMENT NOT NULL, kiekis DOUBLE PRECISION NOT NULL, metai DATE NOT NULL, daigumas INT NOT NULL, kaina NUMERIC(10, 0) NOT NULL, fk_AUGALU_PAVADINIMAI INT NOT NULL, fk_KILMES INT NOT NULL, UNIQUE INDEX id_SEKLOS (id_SEKLOS), INDEX fkc_SEKLOS_AUGALU_PAVADINIMAI (fk_AUGALU_PAVADINIMAI), INDEX fkc_SEKLOS_KILMES (fk_KILMES), PRIMARY KEY(id_SEKLOS)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skiepai (id_SKIEPAI INT AUTO_INCREMENT NOT NULL, fk_AUGALU_PAVADINIMAI INT DEFAULT NULL, fk_KILMES INT NOT NULL, UNIQUE INDEX id_SKIEPAI (id_SKIEPAI), INDEX fkc_SKIEPAI_AUGALU_PAVADINIMAI (fk_AUGALU_PAVADINIMAI), INDEX fkc_SKIEPAI_KILMES (fk_KILMES), PRIMARY KEY(id_SKIEPAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skiepijimo_budai (id_SKIEPIJIMO_BUDAI INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, UNIQUE INDEX id_SKIEPIJIMO_BUDAI (id_SKIEPIJIMO_BUDAI), PRIMARY KEY(id_SKIEPIJIMO_BUDAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skiepyti_augalai (id_SKIEPYTI_AUGALAI INT AUTO_INCREMENT NOT NULL, skiepijimo_data DATE NOT NULL, kiekis INT NOT NULL, fk_SKIEPIJIMO_BUDAI INT NOT NULL, fk_SODINUKAI INT NOT NULL, fk_SKIEPAI INT NOT NULL, UNIQUE INDEX id_SKIEPYTI_AUGALAI (id_SKIEPYTI_AUGALAI), INDEX fkc_SK_AUGALAI_SKIEPIJIMO_BUDAI (fk_SKIEPIJIMO_BUDAI), INDEX fkc_SK_AUGALAI_SODINUKAI (fk_SODINUKAI), INDEX fkc_SK_AUGALAI_SKIEPAI (fk_SKIEPAI), PRIMARY KEY(id_SKIEPYTI_AUGALAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sklypai (id_SKLYPAI INT AUTO_INCREMENT NOT NULL, bendras_plotas DOUBLE PRECISION NOT NULL, produktyvus_plotas DOUBLE PRECISION NOT NULL, skyrius INT NOT NULL, UNIQUE INDEX id_SKLYPAI (id_SKLYPAI), PRIMARY KEY(id_SKLYPAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sodinukai (id_SODINUKAI INT AUTO_INCREMENT NOT NULL, persodinimo_data DATE NOT NULL, kiekis INT NOT NULL, fk_PERSODINIMO_BUDAI INT NOT NULL, fk_SEJINUKAI INT NOT NULL, UNIQUE INDEX id_SODINUKAI (id_SODINUKAI), INDEX fkc_SODINUKAI_SEJINUKAI (fk_SEJINUKAI), INDEX fkc_SODINUKAI_PERSODINIMO_BUDAI (fk_PERSODINIMO_BUDAI), PRIMARY KEY(id_SODINUKAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tech_darbu_pav (id_TECH_DARBU_PAV INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, UNIQUE INDEX id_TECH_DARBU_PAV (id_TECH_DARBU_PAV), PRIMARY KEY(id_TECH_DARBU_PAV)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tech_panaudojimas (id_TECH_PANAUDOJIMAS INT AUTO_INCREMENT NOT NULL, fk_CHEMINIAI_DARBAI INT DEFAULT NULL, fk_TECHNINIAI_DARBAI INT DEFAULT NULL, fk_MED_PANAUDOJIMAS INT DEFAULT NULL, fk_TECHNIKOS_SARASAS INT NOT NULL, UNIQUE INDEX id_TECH_PANAUDOJIMAS (id_TECH_PANAUDOJIMAS), INDEX fkc_TECH_PAN_CHEMINIAI_DARBAI (fk_CHEMINIAI_DARBAI), INDEX fkc_TECH_PAN_TECHNINIAI_DARBAI (fk_TECHNINIAI_DARBAI), INDEX fkc_TECH_PAN_MED_PANAUDOJIMAS (fk_MED_PANAUDOJIMAS), INDEX fkc_TECH_PAN_TECHNIKOS_SARASAS (fk_TECHNIKOS_SARASAS), PRIMARY KEY(id_TECH_PANAUDOJIMAS)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE technikos_sarasas (id_TECHNIKOS_SARASAS INT AUTO_INCREMENT NOT NULL, pavadinimas VARCHAR(255) NOT NULL COLLATE utf16_lithuanian_ci, pirkimo_data DATE NOT NULL, kaina NUMERIC(10, 0) NOT NULL, UNIQUE INDEX id_TECHNIKOS_SARASAS (id_TECHNIKOS_SARASAS), PRIMARY KEY(id_TECHNIKOS_SARASAS)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE techniniai_darbai (id_TECHNINIAI_DARBAI INT AUTO_INCREMENT NOT NULL, data DATE NOT NULL, plotas DOUBLE PRECISION NOT NULL, trukme INT NOT NULL, fk_TECH_DARBU_PAV INT NOT NULL, fk_SODINUKAI INT DEFAULT NULL, fk_SEJINUKAI INT DEFAULT NULL, fk_SKIEPYTI_AUGALAI INT DEFAULT NULL, UNIQUE INDEX id_TECHNINIAI_DARBAI (id_TECHNINIAI_DARBAI), INDEX fkc_TECH_DARBAI_SODINUKAI (fk_SODINUKAI), INDEX fkc_TECH_DARBAI_TECH_DARBU_PAV (fk_TECH_DARBU_PAV), INDEX fkc_TECH_DARBAI_SEJINUKAI (fk_SEJINUKAI), INDEX fkc_TECH_DARBAI_SKIEPYTI_AUGALAI (fk_SKIEPYTI_AUGALAI), PRIMARY KEY(id_TECHNINIAI_DARBAI)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE cheminiai_darbai ADD CONSTRAINT fkc_CH_DARBAI_CH_DARBU_PAV FOREIGN KEY (fk_CH_DARBU_PAV) REFERENCES ch_darbu_pav (id_CH_DARBU_PAV)');
        $this->addSql('ALTER TABLE cheminiai_darbai ADD CONSTRAINT fkc_CH_DARBAI_SEJINUKAI FOREIGN KEY (fk_SEJINUKAI) REFERENCES sejinukai (id_SEJINUKAI)');
        $this->addSql('ALTER TABLE cheminiai_darbai ADD CONSTRAINT fkc_CH_DARBAI_SKIEPYTI_AUGALAI FOREIGN KEY (fk_SKIEPYTI_AUGALAI) REFERENCES skiepyti_augalai (id_SKIEPYTI_AUGALAI)');
        $this->addSql('ALTER TABLE cheminiai_darbai ADD CONSTRAINT fkc_CH_DARBAI_SODINUKAI FOREIGN KEY (fk_SODINUKAI) REFERENCES sodinukai (id_SODINUKAI)');
        $this->addSql('ALTER TABLE darbai ADD CONSTRAINT fkc_DARBAI_CHEMINIAI_DARBAI FOREIGN KEY (fk_CHEMINIAI_DARBAI) REFERENCES cheminiai_darbai (id_CHEMINIAI_DARBAI)');
        $this->addSql('ALTER TABLE darbai ADD CONSTRAINT fkc_DARBAI_DARBUOTOJAI FOREIGN KEY (fk_DARBUOTOJAI) REFERENCES darbuotojai (asmens_kodas)');
        $this->addSql('ALTER TABLE darbai ADD CONSTRAINT fkc_DARBAI_TECHNINIAI_DARBAI FOREIGN KEY (fk_TECHNINIAI_DARBAI) REFERENCES techniniai_darbai (id_TECHNINIAI_DARBAI)');
        $this->addSql('ALTER TABLE darbuotojai ADD CONSTRAINT fkc_DARBUOTOJAI_PAREIGOS FOREIGN KEY (fk_PAREIGOS) REFERENCES pareigos (id_PAREIGOS)');
        $this->addSql('ALTER TABLE kilmes ADD CONSTRAINT fkc_KILMES_MOTININE_BAZE FOREIGN KEY (fk_MOTININE_BAZE) REFERENCES motinine_baze (id_MOTININE_BAZE)');
        $this->addSql('ALTER TABLE med_panaudojimas ADD CONSTRAINT fkc_PANAUDOJIMAS_CHEMINIAI_DARBAI FOREIGN KEY (fk_CHEMINIAI_DARBAI) REFERENCES cheminiai_darbai (id_CHEMINIAI_DARBAI)');
        $this->addSql('ALTER TABLE med_panaudojimas ADD CONSTRAINT fkc_PANAUDOJIMAS_MEDZIAGOS FOREIGN KEY (fk_MEDZIAGOS) REFERENCES medziagos (id_MEDZIAGOS)');
        $this->addSql('ALTER TABLE motinine_baze ADD CONSTRAINT fkc_BAZE_AUGALU_PAVADINIMAI FOREIGN KEY (fk_AUGALU_PAVADINIMAI) REFERENCES augalu_pavadinimai (id_AUGALU_PAVADINIMAI)');
        $this->addSql('ALTER TABLE sejinukai ADD CONSTRAINT fkc_SEJINUKAI_KILMES FOREIGN KEY (fk_KILMES) REFERENCES kilmes (id_KILMES)');
        $this->addSql('ALTER TABLE sejinukai ADD CONSTRAINT fkc_SEJINUKAI_SEKLOS FOREIGN KEY (fk_SEKLOS) REFERENCES seklos (id_SEKLOS)');
        $this->addSql('ALTER TABLE sejinukai ADD CONSTRAINT fkc_SEJINUKAI_SKLYPAI FOREIGN KEY (fk_SKLYPAI) REFERENCES sklypai (id_SKLYPAI)');
        $this->addSql('ALTER TABLE seklos ADD CONSTRAINT fkc_SEKLOS_AUGALU_PAVADINIMAI FOREIGN KEY (fk_AUGALU_PAVADINIMAI) REFERENCES augalu_pavadinimai (id_AUGALU_PAVADINIMAI)');
        $this->addSql('ALTER TABLE seklos ADD CONSTRAINT fkc_SEKLOS_KILMES FOREIGN KEY (fk_KILMES) REFERENCES kilmes (id_KILMES)');
        $this->addSql('ALTER TABLE skiepai ADD CONSTRAINT fkc_SKIEPAI_AUGALU_PAVADINIMAI FOREIGN KEY (fk_AUGALU_PAVADINIMAI) REFERENCES augalu_pavadinimai (id_AUGALU_PAVADINIMAI)');
        $this->addSql('ALTER TABLE skiepai ADD CONSTRAINT fkc_SKIEPAI_KILMES FOREIGN KEY (fk_KILMES) REFERENCES kilmes (id_KILMES)');
        $this->addSql('ALTER TABLE skiepyti_augalai ADD CONSTRAINT fkc_SK_AUGALAI_SKIEPAI FOREIGN KEY (fk_SKIEPAI) REFERENCES skiepai (id_SKIEPAI)');
        $this->addSql('ALTER TABLE skiepyti_augalai ADD CONSTRAINT fkc_SK_AUGALAI_SKIEPIJIMO_BUDAI FOREIGN KEY (fk_SKIEPIJIMO_BUDAI) REFERENCES skiepijimo_budai (id_SKIEPIJIMO_BUDAI)');
        $this->addSql('ALTER TABLE skiepyti_augalai ADD CONSTRAINT fkc_SK_AUGALAI_SODINUKAI FOREIGN KEY (fk_SODINUKAI) REFERENCES sodinukai (id_SODINUKAI)');
        $this->addSql('ALTER TABLE sodinukai ADD CONSTRAINT fkc_SODINUKAI_PERSODINIMO_BUDAI FOREIGN KEY (fk_PERSODINIMO_BUDAI) REFERENCES persodinimo_budai (id_PERSODINIMO_BUDAI)');
        $this->addSql('ALTER TABLE sodinukai ADD CONSTRAINT fkc_SODINUKAI_SEJINUKAI FOREIGN KEY (fk_SEJINUKAI) REFERENCES sejinukai (id_SEJINUKAI)');
        $this->addSql('ALTER TABLE tech_panaudojimas ADD CONSTRAINT fkc_TECH_PAN_CHEMINIAI_DARBAI FOREIGN KEY (fk_CHEMINIAI_DARBAI) REFERENCES cheminiai_darbai (id_CHEMINIAI_DARBAI)');
        $this->addSql('ALTER TABLE tech_panaudojimas ADD CONSTRAINT fkc_TECH_PAN_MED_PANAUDOJIMAS FOREIGN KEY (fk_MED_PANAUDOJIMAS) REFERENCES med_panaudojimas (id_MED_PANAUDOJIMAS)');
        $this->addSql('ALTER TABLE tech_panaudojimas ADD CONSTRAINT fkc_TECH_PAN_TECHNIKOS_SARASAS FOREIGN KEY (fk_TECHNIKOS_SARASAS) REFERENCES technikos_sarasas (id_TECHNIKOS_SARASAS)');
        $this->addSql('ALTER TABLE tech_panaudojimas ADD CONSTRAINT fkc_TECH_PAN_TECHNINIAI_DARBAI FOREIGN KEY (fk_TECHNINIAI_DARBAI) REFERENCES techniniai_darbai (id_TECHNINIAI_DARBAI)');
        $this->addSql('ALTER TABLE techniniai_darbai ADD CONSTRAINT fkc_TECH_DARBAI_SEJINUKAI FOREIGN KEY (fk_SEJINUKAI) REFERENCES sejinukai (id_SEJINUKAI)');
        $this->addSql('ALTER TABLE techniniai_darbai ADD CONSTRAINT fkc_TECH_DARBAI_SKIEPYTI_AUGALAI FOREIGN KEY (fk_SKIEPYTI_AUGALAI) REFERENCES skiepyti_augalai (id_SKIEPYTI_AUGALAI)');
        $this->addSql('ALTER TABLE techniniai_darbai ADD CONSTRAINT fkc_TECH_DARBAI_SODINUKAI FOREIGN KEY (fk_SODINUKAI) REFERENCES sodinukai (id_SODINUKAI)');
        $this->addSql('ALTER TABLE techniniai_darbai ADD CONSTRAINT fkc_TECH_DARBAI_TECH_DARBU_PAV FOREIGN KEY (fk_TECH_DARBU_PAV) REFERENCES tech_darbu_pav (id_TECH_DARBU_PAV)');
        $this->addSql('ALTER TABLE services CHANGE price price INT DEFAULT NULL');
    }
}
