<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use PHPUnit\Framework\TestCase;
use Doctrine\ORM\EntityManager;

class RegisterControllerTest extends WebTestCase
{
    protected $em;
    protected $client;

    protected function setUp()
    {
        parent::setUp();
        $this->client = $this->createClient();
        $this->client->disableReboot();
        $this->em = static::$kernel->getContainer()
            ->get('doctrine')
            ->getManager();
        $this->em->beginTransaction();
        $this->em->getConnection()->setAutoCommit(false);
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        if ($this->em->getConnection()->isTransactionActive())
        {
            $this->em->rollback();
            $this->em->close();
        }
    }

    public function testRegistrationPage()
    {
        //$client = static::createClient();

        $this->client->request('GET', '/register');
        $this->assertEquals(200, $this->client->getResponse()->getStatusCode());
    }

    public function testRegistrationForm()
    {
        //$client = static::createClient();

        $crawler = $this->client->request('GET', '/register');
        $form = $crawler->selectButton('Register')->form();

        // set some values
        $form['user[email]'] = 'Lucas@hotmail.com';
        $form['user[name]'] = 'Lucas';
        $form['user[second_name]'] = 'asd';
        $form['user[password][first]'] = '123456';
        $form['user[password][second]'] = '123456';

        // submit the form
        $this->client->submit($form);
        $this->client->followRedirect();
        //test response
        $this->assertEquals(200,
            $this->client->getResponse()->getStatusCode()
        );
    }
}