<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCkz3o0x\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCkz3o0x/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCkz3o0x.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCkz3o0x\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCkz3o0x\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ckz3o0x',
    'container.build_id' => 'a8ef5090',
    'container.build_time' => 1523743611,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCkz3o0x');
