<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtntgzz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtntgzz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDtntgzz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDtntgzz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDtntgzz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dtntgzz',
    'container.build_id' => 'a839b575',
    'container.build_time' => 1523748578,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtntgzz');
