<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhoaylo\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhoaylo/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXhoaylo.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXhoaylo\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXhoaylo\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Xhoaylo',
    'container.build_id' => '73608c35',
    'container.build_time' => 1523551700,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhoaylo');
